### PR TITLE
Constrain markupsafe<2

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
If this was missing from old versions (or the same version), we may also need [a repodata hot-fix]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/main/recipe#readme )

**Comment by xylar** [comment]
@jakirkham, yes, that would be a good idea.  I figured a working build would be the starting point.

**Comment by jakirkham** [comment]
LGTM. Was there anything else you were wanting to do here or is this ready to merge?

**Comment by xylar** [comment]
It's ready to merge.  Thanks @jakirkham.

**Comment by jakirkham** [comment]
Thanks @xylar! 😄

**Comment by xylar** [comment]
A bit of follow-up here.  I was a little overzealous in the constraint here.  It would have been enough to pin `markupsafe<2.1`, and this is what I will do in the repo patch.
See:
https://github.com/pallets/jinja/issues/1585

**Comment by jakirkham** [comment]
I see. Still protecting against a major version that has seen issues seems reasonable. It's always possible there are other issues that occur with the major version we have yet to see

**Comment by xylar** [comment]
Okay, good point @jakirkham.

**Pull request merged**
